[workspace]
members = [
    "qvk",
    "qforce",
    "qswitch",
    "windowed_tests",
    "qserver",
    "quniverse",
    "qmanager",
]
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
incremental = false