[workspace]
members = [
    "qswitch",
    "qsim",
]
[workspace.package]
version = "0.0.1"
authors = ["Joshua Black"]
[workspace.dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
incremental = false