[package]
name = "examples"
version = "0.0.0"
edition = "2021"
authors = ["Joshua Black"]
publish = false

[dependencies]
pretty_env_logger = "0.4.0"
qforce = {path = "../qforce", version = "0.0.0"}
winit = "0.26.0"
ash = {version = "0.37.0+1.3.209", features = ["linked"]}
